# Generated by Django 3.1 on 2020-08-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('declined', 'Declined'), ('approved', 'Approved')], default='Pending', max_length=10),
        ),
    ]
